version: "3"
services:
  #
  # Jobs
  #

  verify-rpm-amazonlinux-1:
    build:
      context: .
      dockerfile: scripts/ci-docker-images/verifier-amazonlinux-1/Dockerfile
    volumes:
      - $PWD:$PWD
    working_dir: $PWD
    command:
      ["sh", "-ec", "rpm -i target/artifacts/*-x86_64.rpm && vector --version"]

  verify-rpm-amazonlinux-2:
    build:
      context: .
      dockerfile: scripts/ci-docker-images/verifier-amazonlinux-2/Dockerfile
    volumes:
      - $PWD:$PWD
    working_dir: $PWD
    command:
      ["sh", "-ec", "rpm -i target/artifacts/*-x86_64.rpm && vector --version"]

  verify-rpm-centos-7:
    build:
      context: .
      dockerfile: scripts/ci-docker-images/verifier-centos-7/Dockerfile
    volumes:
      - $PWD:$PWD
    working_dir: $PWD
    command:
      ["sh", "-ec", "rpm -i target/artifacts/*-x86_64.rpm && vector --version"]

  verify-deb-artifact-deb-8:
    build:
      context: .
      dockerfile: scripts/ci-docker-images/verifier-deb-8/Dockerfile
    volumes:
      - $PWD:$PWD
    working_dir: $PWD
    command:
      ["sh", "-ec", "dpkg -i target/artifacts/*-amd64.deb && vector --version"]

  verify-deb-artifact-deb-9:
    build:
      context: .
      dockerfile: scripts/ci-docker-images/verifier-deb-9/Dockerfile
    volumes:
      - $PWD:$PWD
    working_dir: $PWD
    command:
      ["sh", "-ec", "dpkg -i target/artifacts/*-amd64.deb && vector --version"]

  verify-deb-artifact-deb-10:
    build:
      context: .
      dockerfile: scripts/ci-docker-images/verifier-deb-10/Dockerfile
    volumes:
      - $PWD:$PWD
    working_dir: $PWD
    command:
      ["sh", "-ec", "dpkg -i target/artifacts/*-amd64.deb && vector --version"]

  verify-deb-artifact-ubuntu-14-04:
    build:
      context: .
      dockerfile: scripts/ci-docker-images/verifier-ubuntu-14-04/Dockerfile
    volumes:
      - $PWD:$PWD
    working_dir: $PWD
    command:
      ["sh", "-ec", "dpkg -i target/artifacts/*-amd64.deb && vector --version"]

  verify-deb-artifact-ubuntu-16-04:
    build:
      context: .
      dockerfile: scripts/ci-docker-images/verifier-ubuntu-16-04/Dockerfile
    volumes:
      - $PWD:$PWD
    working_dir: $PWD
    command:
      ["sh", "-ec", "dpkg -i target/artifacts/*-amd64.deb && vector --version"]

  verify-deb-artifact-ubuntu-18-04:
    build:
      context: .
      dockerfile: scripts/ci-docker-images/verifier-ubuntu-18-04/Dockerfile
    volumes:
      - $PWD:$PWD
    working_dir: $PWD
    command:
      ["sh", "-ec", "dpkg -i target/artifacts/*-amd64.deb && vector --version"]

  verify-deb-artifact-ubuntu-20-04:
    build:
      context: .
      dockerfile: scripts/ci-docker-images/verifier-ubuntu-20-04/Dockerfile
    volumes:
      - $PWD:$PWD
    working_dir: $PWD
    command:
      ["sh", "-ec", "dpkg -i target/artifacts/*-amd64.deb && vector --version"]

  verify-nixos:
    build:
      context: .
      dockerfile: scripts/ci-docker-images/verifier-nixos/Dockerfile
    volumes:
      - $PWD:$PWD
    working_dir: $PWD
    command: ["sh", "-ec", "./scripts/verify-nix.sh && vector --version"]

  target-graph:
    build:
      context: .
      dockerfile: scripts/ci-docker-images/target-graph/Dockerfile
    volumes:
      - $PWD:$PWD
    working_dir: $PWD
    user: $USER
    entrypoint: ./scripts/target-graph.sh
