description = """\
[Amazon CloudWatch][urls.aws_cloudwatch] is Amazon Web Service's (AWS) \
embedded monitoring service designed to monitor AWS resources. It \
automatically integration with AWS infrastructure to help you monitor \
cloud infrastructure, services, and applications thourgh logs, metrics, \
traces, and other operatinal data.\
"""
