description = """\
[Datadog][urls.datadog] is a managed monitoring service for cloud-based \
applications. It allows you to monior servers, databases, and other services \
through a SaaS-based monitoring platform.\
"""
