description = """\
[Docker][urls.docker] is a container platform for defining environments that \
run applications and services. Docker separates your environments from your \
infrastructure, making your application and services portable. This reduces \
infrastructure lock-in, eases deployment, and simplifies development by \
unifying the environment.\
"""
