description = """\
[Stackdriver][urls.gcp_stackdriver], also know as Operations, is Google \
Cloud's embedded monitoring suite designed to monitor cloud infrastructure, \
services, and applications by collecting logs, metrics, traces, and other \
operational data.\
"""
