description = """\
[Apache Kafka][urls.kafka] is an open-source project for streaming data. It \
a distributed commit log, similar to publish-subscribe messaging systems. \
Messages are streamed into Kafka topics and split across 1 or more partitions. \
Data is replicated across multiple brokers ensuring high durability. This \
makes it an excellent candidate for durabily streaming logs, metrics, traces, \
and other observability data.\
"""
