description = """\
[Kubernetes][urls.kubernetes] is a production-grade container orchestration \
platform. It allows you to manage containerized (Dockerized) applications and \
services across a cluster of nodes. It automates resource management, helping \
you to manage and deploy applicationd and services across a variable number \
of machines. Because Kubernetes is abstract, it is critically important that \
you collects, logs, metrics, traces, and other observability data to properly \
monitor the Kubernetes platform.\
"""
