description = """\
[Prometheus][urls.prometheus] is an open-source metrics database for \
monitoring infrastructure, services, and applications. It's built upon a \
unique pull-based model where Prometheus scrapes upstream service endpoints \
that expose internal metrics data. This model increases Prometheus' \
reliability, making it well suited for cloud-based environments where metrics \
data volume can fluctuate rapidly.\
"""
