description = """\
The [Splunk HTTP Event Collector (HEC)][urls.splunk_hec] is a simple and \
efficient way to ingest data into your Splunk Enterprise or Splunk Cloud \
account. As noted in the name, the underlying protocol uses HTTP (or HTTPS), \
a familiar protocol that makes it easy to send data to your Splunk account.\
"""
