description = """\
[StatsD][urls.statsd], created by [Etsy][urls.etsy], is a network daemon that \
listens for metrics data from upstream services, applications, and agents. \
Since its inception, StatsD has grown into a standard for defining metrics \
data where it is widely supported by a variety of metrics solutions.\
"""
