{{- if (empty .Values.existingConfigMap) -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "libvector.configMapName" . }}
  labels:
    {{- include "libvector.labels" . | nindent 4 }}
data:
  # We leave `vector.toml` file name available to let externally managed config
  # maps to provide it.
  managed.toml: |
    # Configuration for vector.
    # Docs: https://vector.dev/docs/

    # Data dir is location controlled at the `DaemonSet`.
    data_dir = "{{ .Values.globalOptions.dataDir }}"

    {{- with .Values.logSchema }}
    [log_schema]
      host_key = "{{ .hostKey }}"
      message_key = "{{ .messageKey }}"
      source_type_key = "{{ .sourceTypeKey }}"
      timestamp_key = "{{ .timestampKey }}"
    {{- end }}

    {{- with .Values.kubernetesLogsSource }}
    {{- if .enabled }}
    # Ingest logs from Kubernetes.
    [sources.{{ .sourceId }}]
      type = "kubernetes_logs"

      {{- if .config }}
      {{- tuple .sourceId .config | include "libvector.vectorSourceConfig" | nindent 4 -}}
      {{- end }}

      {{- with .rawConfig }}
      {{- . | nindent 6 }}
      {{- end }}
    {{- end }}
    {{- end }}

    {{- range $sourceId, $source := .Values.sources }}
    [sources.{{ $sourceId }}]
      type = "{{ $source.type }}"

      {{- if $source.config }}
      {{- tuple $sourceId $source.config | include "libvector.vectorSourceConfig" | nindent 4 -}}
      {{- end }}

      {{- with $source.rawConfig }}
      {{- . | nindent 6 }}
      {{- end }}
    {{- end }}

    {{- range $transformId, $transform := .Values.transforms }}
    [transforms.{{ $transformId }}]
      type = "{{ $transform.type }}"
      inputs = {{ $transform.inputs | toJson }}

      {{- if $transform.config }}
      {{- tuple $transformId $transform.config | include "libvector.vectorSourceConfig" | nindent 4 -}}
      {{- end }}

      {{- with $transform.rawConfig }}
      {{- . | nindent 6 }}
      {{- end }}
    {{- end }}

    {{- range $sinkId, $sink := .Values.sinks }}
    [sinks.{{ $sinkId }}]
      type = "{{ $sink.type }}"
      inputs = {{ $sink.inputs | toJson }}

      {{- if $sink.config }}
      {{- tuple $sinkId $sink.config | include "libvector.vectorSourceConfig" | nindent 4 -}}
      {{- end }}

      {{- with $sink.rawConfig }}
      {{- . | nindent 6 }}
      {{- end }}
    {{- end }}

{{- end }}
