name: Benchmark Suite

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  VERBOSE: true
  CI: true

jobs:
  cancel-previous:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    if: github.ref != 'refs/heads/master'
    steps:
      - uses: styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

  bench:
    name: Bench - Linux
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: make ci-sweep
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Download baseline benchmarks
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: benches.yml
          branch: master
          name: vector-benches
          path: target/criterion
      - run: sudo bash scripts/environment/bootstrap-ubuntu-20.04.sh
      - run: bash scripts/environment/prepare.sh
      - run: echo "::add-matcher::.github/matchers/rust.json"
      - run: make slim-builds
      - run: make bench
      - uses: actions/upload-artifact@v2
        with:
          name: "vector-benches"
          path: "./target/criterion/*"
